version: "3.8"

services:
  app:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    networks:
      - app-network

# Removed the mongo service block
#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - data-volume:/data/db
#     networks:
#       - app-network

networks:
  app-network:
    driver: bridge
# Removed the volumes block
# volumes:
#   data-volume:
